services:

  # --- Frontend ---
  vandvoyage-nodejs-frontend:
    build: ./frontend
    container_name: vandvoyage-nodejs-frontend
    restart: always
    depends_on:
      - vandvoyage-nodejs-backend
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.vandvoyage-nodejs-frontend.loadbalancer.server.port=80"

  # --- Backend ---
  vandvoyage-nodejs-backend:
    build: ./backend
    container_name: vandvoyage-nodejs-backend
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
      - PORT=5000
      - DATABASE_URL=vandvoyage-mongo:27017
      - DATABASE_NAME=${MONGO_DBNAME}
      - DATABASE_USER=${MONGO_ROOT_USERNAME}
      - DATABASE_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - backnet
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.vandvoyage-nodejs-backend.loadbalancer.server.port=5000"

  # --- Database ---
  vandvoyage-mongo:
    image: mongo:latest
    container_name: vandvoyage-mongo
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./mongo_data:/data/db
    environment:
      - TZ=${TZ}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - backnet

networks:
  backnet:
  traefik:
    external: true
